spring:
  application:
    name: ms-users
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: carrefour
            client-secret: NNHY6vE5ymwfLTIW2ifOqYFaKhCpEiOf
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/Parcial/protocol/openid-connect/token
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081
